### ISSUE TITLE
[A_D] Animations character mercenary

### ISSUE THREAD

**Issue by laizpablo** [eloipuertas/ES2016F#102]
Description: 3.9 As a graphic designer, I want a set of animations for the mercenary, to give movement to the character.

Priority: Low

> _Acceptance Criteria:_
> - _There is an IDLE animation._
> - _There is an animation of the mercenary shooting with his bow._
> - _There is an animation of collapsing to the ground._

Estimated time effort: 8h

**Comment by leandroizr** [comment]
@laizpablo Modificar los arqueros para que disparen las flechas en forma de parábola en vez de recto.

**Comment by laizpablo** [comment]
Modificada la animación del arquero

**Comment by amoralca16** [comment]
Rethinking the animation controller. It could be useful if you push your model as it has been created auto (with animator). Sorry for changing methodology. Animation not needed.
