### ISSUE TITLE
[B] Advanced model of a Battering Ram

### ISSUE THREAD

**Issue by leandroizr** [eloipuertas/ES2016F#110]
Description: 3.26. As a designer, I want a model of a battering ram, so I want to have characters who attack. 
Priority: [High priority]

> _Acceptance Criteria:_
> - _Its height is bigger than the height of a human person._
> - _Its length is bigger than the height of a human person._
> - _It has a ravening wolf head._
> - _There is a huge structure holding the battering ram by chains._
> - _The structure has 3 pair of wheels on each side._
> - _It's well integrated._
> - _It looks proportional in the scene._
> - _**It has fire in its mouth**._

Estimated time effort: 4h

**Comment by laizpablo** [comment]
@leandroizr  Falta asignar material en la parte inferior del modelo.

**Comment by laizpablo** [comment]
@leandroizr Mirar que el tamaño del modelo pueda entrar por la puerta de MT

**Comment by leandroizr** [comment]
Arreglado el material sin asignar y la puerta de MT se hará más grande!
