### ISSUE TITLE
[B] Texturization of the Battering Ram

### ISSUE THREAD

**Issue by leandroizr** [eloipuertas/ES2016F#112]
Description : 3.27. As a designer, I want the texturization of the battering ram, so I want an attractive design.
Priority: [Medium priority]

> _Acceptance Criteria:_
> - _It’s made of steel._
> - _It has the texturization of the fire in the mouth._
> - _The structure and the wheels are made of wood._
> - _The chains are made of steel._

Estimated time effort: 2h

**Comment by laizpablo** [comment]
@leandroizr Revisar textura del cuerpo en Unity

**Comment by leandroizr** [comment]
Ahora se ve bien las texturas en unity.
