### ISSUE TITLE
[A][D] Animations tower orc archer

### ISSUE THREAD

**Issue by sbatllpa9** [eloipuertas/ES2016F#120]
Description: 3.12 As a graphic designer, I want a set of animations for the tower, to show how the defense is beeing destroyed.

Priority: Medium

> _Acceptance Criteria:_
> * _There is an IDLE animation._
> * _There is an animation of the tower when it is attacked (destruction animation)._

Estimated time effort: 5h

**Comment by amoraca16** [comment]
Already implemented, if no changes on animation the issue can be closed.

**Comment by amoralca16** [comment]
@sbatllpa9   
- No projectile on the prefab. 
- Please attack and recharge only once. Take mercenary as an example.

**Comment by sbatllpa9** [comment]
This issue refers to animations that don't hae to be done. About the orc archer animations we have the issue 168. I close this issue because of that.
