### ISSUE TITLE
[B] (SPRINT 3) Animation of Trebuchet throwing a rock

### ISSUE THREAD

**Issue by leandroizr** [eloipuertas/ES2016F#128]
Description : 3.15 Basic animation of the Trebuchet throwing a rock.

Priority: [Low priority]

> _Acceptance Criteria:_
> - _There is an animation of the trebuchet throwing a rock._

Estimated time effort: 6h

**Comment by laizpablo** [comment]
@leandroizr Adaptar la animación a las leyes de la física.
