### ISSUE TITLE
[B] The texturization of the orc

### ISSUE THREAD

**Issue by apalasce7** [eloipuertas/ES2016F#132]
Description : 3.18. As a designer, I want the texturization of the orcs, so I want an attractive design.

Priority: [Medium priority]

> _Acceptance Criteria:_
* _The armor is made with steel._
* _The orc scimitar made with steel._

Estimated time effort: 5h

**Comment by aduenape7** [comment]
@apalasce7 
- Prueba a no utilizar las costuras ya que te producen cortes muy marcados en la textura
- Una vez quitadas, no utilices el despliegue automático ya que no te ayuda a mapear correctamente la textura.
- Utiliza diferentes materiales en tu objeto para separa la piel de todas las otras partes
- Por último, para facilitar la tarea de seleccionar/deseleccionar vértices cuando aplicas los diferentes materiales utiliza los grupos de vértices que proporciona Blender que permite seleccionar con un click un conjunto determinado de botones
