### ISSUE TITLE
[B-C/D] Basic animation (idle) of the tower (minas tirith)

### ISSUE THREAD

**Issue by apalasce7** [eloipuertas/ES2016F#167]
4.3. As a designer, I want a set of animations of the main tower (Minas Tirith), so I want to see how the tower is damaged. [Low priority]

> _Acceptance Criteria:_
> - _There is an IDLE animation._

Estimatted Time: 4h

**Comment by amoralca16** [comment]
@apalasce7  This should be implemented as the Isengard Tower, see the Damage prefabs inside the tower and the GameManager managing it.
