### ISSUE TITLE
[A-C/D] BUG Animations character orc archer

### ISSUE THREAD

**Issue by sbatllpa9** [eloipuertas/ES2016F#168]
BUG => Simplify the animations of the character orc archer (less animation points).

Description: 3.9 As a graphic designer, I want a set of animations for the orc archer, to give movement to the character. (only IDLE and ATTACK animations)

Priority: High

Estimated time effort: 4h

**Comment by AlbertGuzman** [comment]
Check the animation of OrchArcher. [devel_fix_animationOrchArcher]

**Comment by amoralca16** [comment]
It will be implemented by me by animator due to OrcArcher is my assigned animation.
See issue #120 https://github.com/eloipuertas/ES2016F/issues/120
Do not new issues based on the already created ones. Tag it as a bug instead. (Only if it concerns to you)

**Comment by sbatllpa9** [comment]
Now (Sprint 5) TODO in the BUG:
1) Correct attack animation to only one attack movement.
2) Add arrow and recharge animation
3) Import it to unity

Estimated time effort: 6h
