### ISSUE TITLE
[D/C] Slotation of the maps by scripting

### ISSUE THREAD

**Issue by amoralca16** [eloipuertas/ES2016F#173]
Path detection color visualitation.
Estimated effort 6h.

**Comment by amoralca16** [comment]
Somebody broke this at all. Deleting all.

**Comment by amoralca16** [comment]
@deceiver91 could you readd the slots of MinasTirith please?

**Comment by EnLaLuna91** [comment]
@amoraca16 yes, right now I was going to create a bug to fix this, but I've already seen that this one is created.
