### ISSUE TITLE
[A/B/C/D] Test Game

### ISSUE THREAD

**Issue by EnLaLuna91** [eloipuertas/ES2016F#189]
As a player I want a game that I can play it

> _Acceptance Criteria_:
* _Detect all critical bugs and assign who fix it._ 

Estimated effort: 10h

**Comment by laizpablo** [comment]
- En escena principal no hi ha una base amb les torres
- En el menú d'opcions no funciona els controls de volum
- En el menú per escollir MT o I no funciona l'opció de Return to the main menu
- En l'escena MT es queda clavat el trabuquet
- Quan a MT i has perdut i li dónes a submit el joc és tenca
- A l'escena de MT només dispara el trabuquet
- A l'escena de MT no es poden vendre els defensors

- A l'escena de I Saruman no es pot arrossegar a l'escena
- A l'escena de I orc warior no es pot arrossegar a l'escena
- A l'escena de I el mercenary només ataca un cop però continua girant

- Hi ha unitats que no ataquen a les dues escenes
- El 7/9 continua sense modificar-se

**Comment by jespinlo10** [comment]
En el menú per escollir MT o I no funciona l'opció de Return to the main menu---FIXED

**Comment by EnLaLuna91** [comment]
- Unidades enemigas deberían de poder atravesarse entre ellas, si no las unidades más lentas relentizan las rápidas y además puede dar problemas con el camino

**Comment by NataliaConesa** [comment]
BUGS 19/12/16
- velocidad para que no choquen y delay OK
- cambios de escena OK
- termine juego OK

**Comment by mpQuintana** [comment]
Al vender una torre se sigue haciendo daño a los enemigos al pasar por ahi

**Comment by mragelfe7** [comment]
Fixing enemy not moving will be destroyed!
