### ISSUE TITLE
[A] Model character orc archer

### ISSUE THREAD

**Issue by sbatllpa9** [eloipuertas/ES2016F#26]
Description: 3.7 Design for the model of an orc archer (defense for the battle of Isengard)

Priority: High

> _Acceptance Criteria:_
> - _Orcs are smaller than the ents, and huorns._
> - _Orcs are bigger than the humans, elfos and hobbits._
> - _Orcs have to wear armor._
> - _Orcs have orc aspect._
> - _The orc archer uses a bow to fight._

Estimated time effort: 16h

**Comment by juliagarriga** [comment]
Code Review:
1. Too many vertices.
2. Too big for integration.
3. Problem with axis in different objects
