### ISSUE TITLE
[B] Basic model tower (Minas Tirith)

### ISSUE THREAD

**Issue by apalasce7** [eloipuertas/ES2016F#29]
Description : 4.1 Basic model tower (Minas Tirith)

Priority: [High priority]

> _Acceptance Criteria:_
> - _The shape of the main tower is Circular._
> - _Have six floors, each one inside and on top of another._
> - _On the sixth floor, stands a ravine._
> - _The main entrance has two large towers._
> - _On each floor, there are several houses and towers._
> - _The tower is built in a mountain_

Estimated time effort: 8h

**Comment by marccasillas** [comment]
@apalasce7 Añadir un plano para que no se va que la montaña esta vacia.

**Comment by apalasce7** [comment]
Sprint 2: Modeling & Integration.

> _Acceptance Criteria:_
> - _It's well integrated._
> - _In the ravine there is an eagle perched on the end._
> - _It looks proportional in the scene._

Estimated time effort: 4h
