### ISSUE TITLE
[B] Basic model Trebuchet (Catapult)

### ISSUE THREAD

**Issue by leandroizr** [eloipuertas/ES2016F#30]
Description : 3.13 Basic model Trebuchet (Catapult)

Priority: [High priority]

> _Acceptance Criteria:_
> - _It has a long beam that pivots around the axle that divides the beam into a long and short arm._
> - _The projectile holder is connected with the end of the long arm by a long slim._
> - _The counterweight  is positioned at the end of the short arm._
> - _The length of the long beam is bigger than the height of a human person._
> - _The size of the long arm of the beam is bigger than the size of its short arm._
> - _The projectile holder is bigger than the size of a human person._

Estimated time effort: 8h

**Comment by leandroizr** [comment]
Sprint 2: Modeling & Integration.

> _Acceptance Criteria:_
> - _It's well integrated._
> - _It looks proportional in the scene._

Estimated time effort: 4h

**Comment by aduenape7** [comment]
@leandroizr
- _Junta las figuras metálicas con las de madera para facilitar el diseño de las animaciones y la integración en Unity._
- _Hay cuardas con y sin material, unifica el diseño de ellas_
