### ISSUE TITLE
[B] Texturization of the basic model of the tower (Minas tirith).

### ISSUE THREAD

**Issue by apalasce7** [eloipuertas/ES2016F#36]
Description : 4.2 Texturization of the basic model of the tower (Minas tirith).

Priority: [Medium priority]

> _Acceptance Criteria:_
> - _Tower made of stone and white brick._

Estimated time effort: 8h

**Comment by marccasillas** [comment]
@apalasce7 Añadir textura al plano.

**Comment by apalasce7** [comment]
Sprint 2: Texturization & Integration.

> _Acceptance Criteria:_
> - _Best texture mapping technique._

Estimated time effort: 4h
