### ISSUE TITLE
[A] Model character ent

### ISSUE THREAD

**Issue by aduenape7** [eloipuertas/ES2016F#38]
3.16 As a graphic designer, I want the model of a high ent (Treebeard), to have characters who attack.

Priority: High

> _Acceptance Criteria:_
> - _Ents are bigger than the other characters._
> - _Ents have humanized tree aspect._

Estimated time effort: 16h

**Comment by leandroizr** [comment]
@aduenape7  
- _Redimensiona el tamaño del Ent al que habíamos acordado del Design Notes._
- _Agranda un poco los brazos porque son muy delgados._
- _La cabeza quizás debería ser un poco más grande, puedes usar el modo de escultura para ello hay varias opciones como el smooth por ejemplo._

**Comment by apalasce7** [comment]
@aduenape
- _Hacer que le salgan ramas del cuerpo al ent._
