### ISSUE TITLE
[C]   Illuminate scene.

### ISSUE THREAD

**Issue by mragelfe7** [eloipuertas/ES2016F#51]
Explination: Illuminate the scene realistically and according to the model objects.

Tirith -> afternoon evening
Isengard -> evening night

Description: 7.1 As a designer I want to make some levels and maps. [High Priority]

> _Acceptance Criteria:_
> - _The model objects can see quite good in the scene._
> - _There is no bugs._ 

Estimated time effort: 5h

**Comment by Pherresa** [comment]
Lower the intesity of the spotlight (the battle take place at night) and also lower the ambient component to make the scene darker. Everything else is fine!

**Comment by mragelfe7** [comment]
Change the directional light of the scene tiriht, i., e., change it to neutral light!
