### ISSUE TITLE
[C][D]   Camera behaviour for the game.

### ISSUE THREAD

**Issue by jespinlo10** [eloipuertas/ES2016F#55]
Explination: Zoom, Rotate, Pan the scene game when the mouse buttons are clicked. 

Acceptance Criteria:

The player can zoom, pan and rotate the camera in the scene game. 
There is no bugs.
Estimated time effort: 8h

**Comment by jespinlo10** [comment]
Assign to @jsoriaso7 to improve zoom in/out behaviour

**Comment by amoralca16** [comment]
Camera changed by me check it and close the issue if you like it. Or make it even better.
