### ISSUE TITLE
[C] Create/Update map for convert map in objects in C#

### ISSUE THREAD

**Issue by EnLaLuna91** [eloipuertas/ES2016F#66]
7.1 As a designer I want to make some levels and maps. [High Priority]

> _Acceptance Criteria:_
> - _Convert in C# Object._
> - _It has no bugs._

Estimated effort: 6h

**Comment by laizpablo** [comment]
@deceiver91  Gestionar zona para torre principal. Hablar en conjunto con los diseñadores de cada torre y encontrar soluciones personalizadas.

**Comment by laizpablo** [comment]
@deceiver91 Texturas del mapa. Tanto del camino como de la superficie donde estaran las unidades.
