### ISSUE TITLE
[A] Realistic model Orthanc

### ISSUE THREAD

**Issue by laizpablo** [eloipuertas/ES2016F#7]
- 4.1 As a graphic designer, I want a model of the main tower (Orthanc), to have a tower to defend. [High Priority]

> _Acceptance Criteria:_
> - _The shape of the main tower is a cross._
> - _The tower is composed of four adjunctive columns._
> - _The columns are high._
> - _At the top of the tower, there are four horns._
> - _The horns surround a platform._
> - _The tower grows up upside a round platform with stairs._

Estimated time effort: 16h

**Comment by leandroizr** [comment]
@laizpablo Ajustar la muralla de la torre Isengard en unity. Y eliminar la base de la torre.

**Comment by leandroizr** [comment]
@laizpablo La muralla y la torre deberían seguir el mismo estilo.

**Comment by laizpablo** [comment]
La muralla y la torre ya siguen el mismo estilo. Para ello he modificado la muralla.

**Comment by laizpablo** [comment]
Ajustada la muralla de la torre Isengard en unity. Y eliminada la base de la torre.
