### ISSUE TITLE
[A] Texturization Orthanc Tower

### ISSUE THREAD

**Issue by laizpablo** [eloipuertas/ES2016F#74]
- 4.2. As a graphic designer, I want the texturization of the main tower (Orthanc), to have a realistic design. [Medium priority]

> _Acceptance Criteria:_
> - _Tower made of black stone._

Estimated time effort: 4h

**Comment by EnLaLuna91** [comment]
@laizpablo Cambiar ruta de las texturas, para las coja bien (estan en la ruta antigua).

**Comment by EnLaLuna91** [comment]
@laizpablo Centrar la torre con el centro del la base.

**Comment by laizpablo** [comment]
Modificado!
