### ISSUE TITLE
[A] Texturization mercenary character

### ISSUE THREAD

**Issue by laizpablo** [eloipuertas/ES2016F#75]
- 3.14 As a graphic designer, I want the texturization of the mercenary human, so I want a realistic design. [Medium priority]

> _Acceptance Criteria:_
> - _The armor is made of steel._
> - _The sword is made of steel._

Estimated time effort: 8h

**Comment by EnLaLuna91** [comment]
@laizpablo Modificar el casco del mercenario para que no sea tan IIGM

**Comment by EnLaLuna91** [comment]
@laizpablo Al importar el mercenario al Unity 3D, no se ve el fuego y Texturas de la cara y flechas (Rutas)

**Comment by laizpablo** [comment]
He arreglado la textura de la cara y de las flechas,
El fuego no he conseguido encontrar el problema.

**Comment by laizpablo** [comment]
Problema del fuego solucionado. Ahora se hace con prefabs ya importados en unity,
