### ISSUE TITLE
[A] Animations character orc archer

### ISSUE THREAD

**Issue by sbatllpa9** [eloipuertas/ES2016F#82]
Description: 3.9 As a graphic designer, I want a set of animations for the orc archer, to give movement to the character. (only IDLE and ATTACK animations)

Priority: High

> _Acceptance Criteria:_
> - _There is an IDLE animation._
> - _There is an animation of the orc shooting with his bow._

Estimated time effort: 8h

**Comment by NataliaConesa** [comment]
Code Review:
1. overstate idle animation. Low prority (to do when scaffolding is done)
