### ISSUE TITLE
[B] Model of winged beast

### ISSUE THREAD

**Issue by NataliaConesa** [eloipuertas/ES2016F#85]
3.20. As a designer, I want a model of a winged beast with Nazgul, so I want to have characters who attack. [High priority]

> Acceptance Criteria:
> Its shape is like a dragon.
> It is three times larger than a human.
> It has the holed wings.
> It has a long neck.

Estimate effort: 6h

**Comment by NataliaConesa** [comment]
Sprint 3: Refine Model

**Comment by sbatllpa9** [comment]
Code Review:
1. Add tongue to the model. [Medium Priority]
2. Reduce number of vertices if it is possible. [Low priority]
