### ISSUE TITLE
[A] Texturization Ent character

### ISSUE THREAD

**Issue by aduenape7** [eloipuertas/ES2016F#87]
- 3.17 As a graphic designer, I want the texturization of the ent (Treebeard), so I want a realistic design. [Medium priority]

> _Acceptance Criteria:_
> - _Treebeard is green._
> - _Treebeard is made of wood and sheet._

Estimated time effort: 8h

**Comment by leandroizr** [comment]
@aduenape7  
- _Falta material: Asegurate que el material tenga el mismo nombre que la textura._

**Comment by aduenape7** [comment]
Refined in sprint 3 as it doesn't has an appropiate UV mapping

**Comment by apalasce7** [comment]
@aduenape 
- _Usar metodo de cortes por costuras en blender para definir mejor el UV mapping._
- _Los pies y brazos se ven oscuros sin una textura adecudada._
