### ISSUE TITLE
[A] Mercenary base

### ISSUE THREAD

**Issue by EnLaLuna91** [eloipuertas/ES2016F#92]
- 3.13 As a graphic designer, I want the model of a mercenaries human with armor in a base, to have characters who defend. [Medium priority]

> _Acceptance Criteria:_
> - _The base will have a fire in the center._
> - _The base will have a group of mercernary above._

Estimated time effort: 4h

**Comment by leandroizr** [comment]
@laizpablo Modificar base para añadirle sacos de arena y de textura en vez de verde ponerle que se parezca al de la arena.

**Comment by leandroizr** [comment]
@laizpablo Ajustar el fuego del centro de la base para que se vea en 3D

**Comment by laizpablo** [comment]
Ya esta creada una nueva base con las especificaciones:
- 3 murallas de sacos de tierra
- suelo de arena

**Comment by laizpablo** [comment]
Ya está ajustado el fuego del centro de la base para crear un efecto más en 3D.
